language: scala
jdk:
  - openjdk8

script: 
  - mkdir documentation
  - sbt "runMain pamflet.Pamflet src documentation"
  - cp .gitignore.except_documentation .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: source
    
