language: scala
jdk:
  - openjdk8

script: sbt "runMain pamflet.Pamflet src documentation"

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: source
    
